### ISSUE TITLE
Make baseUrl abstract in PageObject

### ISSUE THREAD

**Issue by nadvolod** [titusfortner/sauce_framework#2]
I think that we should force users to override the `baseUrl` in `BasePage` when they extend `PageObject`
Otherwise, this error is thrown "com.saucelabs.framework.exceptions.PageObjectException: url or path with baseURL must be defined to visit Page Object class pages.aig.AIGHomePage"

**Comment by titusfortner** [comment]
ahhh, is that how we get around that error? :)
I kept hack/tweaking things until something worked. I'll try this.

**Comment by titusfortner** [comment]
You can't make a field abstract like this. 
I think this issue stems from #3 
So fixing that one should fix this one.
