### ISSUE TITLE
PageObject should be able to figure out which url to visit without configuration

### ISSUE THREAD

**Issue by nadvolod** [titusfortner/sauce_framework#3]
Currently, I think that the user needs to define a `visit()` in their page for it to work. `PageObject` should be able to figure this out by combining the `baseUrl` + the `@OnPage(url = "/individual")`
This was actually really confusing to me because I assumed that it would work out of the box. Rather, I had to implement a visit() in my child page to fix the problem. Seems unecessary. 
```
    public void visit()
    {
        browser.get(getBaseURL());
    }
```

**Comment by titusfortner** [comment]
As discussed, the current code it should be `@OnPage(path = "/individual")` I'll update it to be `UrlPath=` instead.

**Comment by titusfortner** [comment]
ok, so I adjusted name and made capitalization consistent. It is now:
`urlPath` and `baseUrl`
