### ISSUE TITLE
Make @OnPage(url, elements) mandatory

### ISSUE THREAD

**Issue by nadvolod** [titusfortner/sauce_framework#4]
I think that we should force the users to define at least those two arguments. I can't think of a use case where someone wouldn't define the `url`. And if they want to do a valuable check to make sure that the user is `onPage()`, then they should define an element. Doing the check solely on URL can be pointless as a website can come up, without actually being to render.

**Comment by titusfortner** [comment]
The point is that each user can decide for themselves what it means to be on a page, we don't want to force them to do anything that isn't necessary.

Using a `isOnPage()` method to determine "has the page finished loading?" is the wrong usage for it, in my opinion. It's better to attempt that synchronization when taking an action on the element you want to use on that page. Fewer wire calls.

The reason for the `elements` implementation is to handle things like modals or single page apps when there is no title/url to compare.

My primary usage of `isOnPage()` would actually be the waiting for it not to be on the page so that the stack trace for the problem ends up in :

```Java
public void submitForm(DataObject data) {
   fillForm(data);
   submitButton.click();
  try {
    Wait.until( {} -> !this.isOnPage() )
   } catch (TimeoutException e) {
    String message = "Expected submitting form to work on:  " + this.getClass() + " found error: " + errorMessage.getText();
     throw new PageObjectException(message);
}
```

**Comment by nadvolod** [comment]
@titusfortner so then maybe we need a method called `isPageLoaded()`? That could then be used in situations like this:
```
    @Then("the user sees the Business page render sucessfully")
    public void theUserSeesTheBusinessPageRenderSuccessfully() {
        assertTrue(businessPage.isOnPage());
    }
```
This has been my pattern throughout all of the tests. And rather than calling `isOnPage()`, we call `isPageLoaded()` which will make sure that the page is rendered.

**Comment by titusfortner** [comment]
`isPageLoaded()` has no meaning in today's web. At best it results in unnecessary wire calls. I shouldn't care if other elements are on the page, I should only care if the element I want to interact with is on the page and interactable, and this framework is designed to wait for that element to receive the action as best as it can. If there are dynamic JS things going on that affect it, then we'll need to deal with those separately.

**Comment by nadvolod** [comment]
Oh, that's an interesting point of view. So you are suggesting that in today's web, we should only check:
- if we are on the right page
- is element that I want to interact with in good state. And this happens automatically when we do a `click()` for example.
Did I summarize that right? @titusfortner

**Comment by titusfortner** [comment]
Yes, and the more I think about it, the more I think checking if you are on a page is only useful for synchronizing leaving the "page/modal" or checking status when rescuing an exception of some kind. Like, you shouldn't be using it to determine what actions to take (non-deterministic), and there are only limited scenarios I can think of where it is useful information to have.

It's still a useful method, but not nearly as essential as it was even 5 years ago.

**Comment by nadvolod** [comment]
You bring about good points @titusfortner . So along these lines, it sounds like `elements` shouldn't be part of the configuration as it's not relevant?
